<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ivone Humacata">

<title>DISEÑO EXPERIMENTAL</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="001.dca_files/libs/clipboard/clipboard.min.js"></script>
<script src="001.dca_files/libs/quarto-html/quarto.js"></script>
<script src="001.dca_files/libs/quarto-html/popper.min.js"></script>
<script src="001.dca_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="001.dca_files/libs/quarto-html/anchor.min.js"></script>
<link href="001.dca_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="001.dca_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="001.dca_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="001.dca_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="001.dca_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#fundamentacion" id="toc-fundamentacion" class="nav-link active" data-scroll-target="#fundamentacion"><span class="toc-section-number">0.1</span>  FUNDAMENTACION</a></li>
  <li><a href="#diseño-completamente-aleatorizado-dca-completely-randomized-designs-with-one-factor-crd" id="toc-diseño-completamente-aleatorizado-dca-completely-randomized-designs-with-one-factor-crd" class="nav-link" data-scroll-target="#diseño-completamente-aleatorizado-dca-completely-randomized-designs-with-one-factor-crd"><span class="toc-section-number">1</span>  DISEÑO COMPLETAMENTE ALEATORIZADO (DCA)/ COMPLETELY RANDOMIZED DESIGNS WITH ONE FACTOR (CRD)</a>
  <ul class="collapse">
  <li><a href="#objetivos-de-aprendizaje" id="toc-objetivos-de-aprendizaje" class="nav-link" data-scroll-target="#objetivos-de-aprendizaje"><span class="toc-section-number">1.1</span>  OBJETIVOS DE APRENDIZAJE</a></li>
  <li><a href="#introduccion" id="toc-introduccion" class="nav-link" data-scroll-target="#introduccion"><span class="toc-section-number">1.2</span>  INTRODUCCION</a></li>
  <li><a href="#supuestos" id="toc-supuestos" class="nav-link" data-scroll-target="#supuestos"><span class="toc-section-number">1.3</span>  SUPUESTOS</a></li>
  <li><a href="#modelo-matematico" id="toc-modelo-matematico" class="nav-link" data-scroll-target="#modelo-matematico"><span class="toc-section-number">1.4</span>  MODELO MATEMATICO</a></li>
  <li><a href="#ejemplo-1-echeverria-sp." id="toc-ejemplo-1-echeverria-sp." class="nav-link" data-scroll-target="#ejemplo-1-echeverria-sp."><span class="toc-section-number">1.5</span>  EJEMPLO 1 ~ ECHEVERRIA SP.</a>
  <ul class="collapse">
  <li><a href="#repeticion-y-aleatorizacion" id="toc-repeticion-y-aleatorizacion" class="nav-link" data-scroll-target="#repeticion-y-aleatorizacion"><span class="toc-section-number">1.5.1</span>  REPETICION Y ALEATORIZACION</a></li>
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link" data-scroll-target="#objetivo"><span class="toc-section-number">1.5.2</span>  OBJETIVO</a></li>
  <li><a href="#unidades-experimentales" id="toc-unidades-experimentales" class="nav-link" data-scroll-target="#unidades-experimentales"><span class="toc-section-number">1.5.3</span>  UNIDADES EXPERIMENTALES</a></li>
  <li><a href="#unidades-de-observacion" id="toc-unidades-de-observacion" class="nav-link" data-scroll-target="#unidades-de-observacion"><span class="toc-section-number">1.5.4</span>  UNIDADES DE OBSERVACION</a></li>
  <li><a href="#variable-respuesta-o-variable-dependiente" id="toc-variable-respuesta-o-variable-dependiente" class="nav-link" data-scroll-target="#variable-respuesta-o-variable-dependiente"><span class="toc-section-number">1.5.5</span>  VARIABLE RESPUESTA O VARIABLE DEPENDIENTE</a></li>
  <li><a href="#variable-independiente" id="toc-variable-independiente" class="nav-link" data-scroll-target="#variable-independiente"><span class="toc-section-number">1.5.6</span>  VARIABLE INDEPENDIENTE</a></li>
  <li><a href="#variables-ocultas" id="toc-variables-ocultas" class="nav-link" data-scroll-target="#variables-ocultas"><span class="toc-section-number">1.5.7</span>  VARIABLES OCULTAS</a></li>
  <li><a href="#analisis-exploratorio" id="toc-analisis-exploratorio" class="nav-link" data-scroll-target="#analisis-exploratorio"><span class="toc-section-number">1.5.8</span>  ANALISIS EXPLORATORIO</a></li>
  <li><a href="#modelo-matematico-1" id="toc-modelo-matematico-1" class="nav-link" data-scroll-target="#modelo-matematico-1"><span class="toc-section-number">1.5.9</span>  MODELO MATEMATICO</a></li>
  <li><a href="#hipotesis-de-planteo" id="toc-hipotesis-de-planteo" class="nav-link" data-scroll-target="#hipotesis-de-planteo"><span class="toc-section-number">1.5.10</span>  HIPOTESIS DE PLANTEO</a></li>
  <li><a href="#suma-de-cuadrados" id="toc-suma-de-cuadrados" class="nav-link" data-scroll-target="#suma-de-cuadrados"><span class="toc-section-number">1.5.11</span>  SUMA DE CUADRADOS</a></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova"><span class="toc-section-number">1.5.12</span>  ANOVA</a></li>
  <li><a href="#verificacion-de-los-supuestos-del-anova" id="toc-verificacion-de-los-supuestos-del-anova" class="nav-link" data-scroll-target="#verificacion-de-los-supuestos-del-anova"><span class="toc-section-number">1.5.13</span>  VERIFICACION DE LOS SUPUESTOS DEL ANOVA</a></li>
  <li><a href="#conclusiones-del-modelo-planteado" id="toc-conclusiones-del-modelo-planteado" class="nav-link" data-scroll-target="#conclusiones-del-modelo-planteado"><span class="toc-section-number">1.5.14</span>  CONCLUSIONES DEL MODELO PLANTEADO</a></li>
  <li><a href="#confiabilidad-del-modelo" id="toc-confiabilidad-del-modelo" class="nav-link" data-scroll-target="#confiabilidad-del-modelo"><span class="toc-section-number">1.5.15</span>  CONFIABILIDAD DEL MODELO</a></li>
  </ul></li>
  <li><a href="#ejemplo-2-terneza-de-carne" id="toc-ejemplo-2-terneza-de-carne" class="nav-link" data-scroll-target="#ejemplo-2-terneza-de-carne"><span class="toc-section-number">1.6</span>  EJEMPLO 2 ~ TERNEZA DE CARNE</a></li>
  <li><a href="#preguntas-orientadoras" id="toc-preguntas-orientadoras" class="nav-link" data-scroll-target="#preguntas-orientadoras"><span class="toc-section-number">1.7</span>  PREGUNTAS ORIENTADORAS</a></li>
  <li><a href="#recursos-recomendados" id="toc-recursos-recomendados" class="nav-link" data-scroll-target="#recursos-recomendados"><span class="toc-section-number">1.8</span>  RECURSOS RECOMENDADOS</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DISEÑO EXPERIMENTAL</h1>
<p class="subtitle lead">Facultad de Ciencias Agrarias - UNJu. Año 2023</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ivone Humacata </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="fundamentacion" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="fundamentacion"><span class="header-section-number">0.1</span> FUNDAMENTACION</h2>
<p>Diseño Experimental es usado para construir modelos que describan la relación de una variable respuesta de interés y una o más variables independientes. Dichos modelos son utilizados para predecir la respuesta, de este modo permite al experimentador resolver importantes aspectos acerca del sistema bajo estudio. Consecuentemente, el desarrollo del modelo en la estimación de la respuesta y la predicción es de suma importancia. La asignatura está orientada hacia los principios y diseños fundamentales de investigación. Estas bases constituyen los elementos necesarios para que se apliquen estrategias útiles y eficientes especialmente en el área de bromatología y biología.</p>
</section>
<section id="diseño-completamente-aleatorizado-dca-completely-randomized-designs-with-one-factor-crd" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> DISEÑO COMPLETAMENTE ALEATORIZADO (DCA)/ COMPLETELY RANDOMIZED DESIGNS WITH ONE FACTOR (CRD)</h1>
<section id="objetivos-de-aprendizaje" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="objetivos-de-aprendizaje"><span class="header-section-number">1.1</span> OBJETIVOS DE APRENDIZAJE</h2>
<ol type="1">
<li><p>Aplicar los pasos necesarios para implementar un diseño completamente aleatorizado en un estudio experimental.</p></li>
<li><p>Conocer las técnicas para asignar aleatoriamente los tratamientos a los grupos de muestra en un diseño completamente aleatorizado.</p></li>
<li><p>Aplicar ANOVA para un DCA con software estadístico.</p></li>
<li><p>Interpretar y comunicar correctamente los resultados del ANOVA en un diseño completamente aleatorizado.</p></li>
</ol>
</section>
<section id="introduccion" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="introduccion"><span class="header-section-number">1.2</span> INTRODUCCION</h2>
<p>El diseño completamente aleatorizado es uno de los diseños experimentales más simples y comunes. En este diseño, los sujetos o unidades experimentales se asignan de forma aleatoria a los diferentes tratamientos o grupos. Luego, cada grupo está sujeto a uno de los niveles o valores únicos del factor tratamiento. El objetivo es controlar la variabilidad entre las unidades experimentales y evaluar el efecto de los tratamientos en la variable de respuesta.</p>
<p>Este diseño debe utilizarse cuando solo hay un factor y las unidades experimentales son homogeneas.</p>
<p>Específicamente, prueba la hipótesis nula:</p>
<p><span class="math display">
Ho: \mu_1=\mu_2=\mu_3 = ... = \mu_i
</span></p>
<p>Donde <span class="math inline">\mu</span> es la media de tratamiento e <span class="math inline">i</span> es la cantidad de tratamientos (o grupos). Si el ANOVA a un factor (Analysis of variance) arroja un resultado estadísticamente significativo, se rechaza la hipótesis nula y se concluye que <em>al menos una de las medias de tratamiento es significativamente diferente a las demas</em> desde el punto de vista estadístico. Para determinar cuáles tratamientos difieren entre sí, se debe utilizar una prueba post hoc de comparación de medias.</p>
</section>
<section id="supuestos" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="supuestos"><span class="header-section-number">1.3</span> SUPUESTOS</h2>
<p>Para que los resultados de este análisis sean válidos, se deben cumplir los siguientes supuestos:</p>
<ol type="1">
<li><strong>Normalidad de los residuos:</strong> los residuos del modelo deben seguir una distribución normal. Esto implica que los datos dentro de cada grupo deben aproximarse a una distribución normal.<br>
</li>
<li><strong>Varianzas homogeneas:</strong> la varianza de las respuestas en cada tratamiento debe ser constante. Esto implica que la dispersión de los datos debe ser similar en cada grupo.<br>
</li>
<li><strong>Independencia de los errores:</strong> las observaciones en cada tratamiento deben ser independientes entre sí. Esto implica que el resultado de una observación no debe influir en el resultado de otras observaciones.<br>
</li>
</ol>
</section>
<section id="modelo-matematico" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="modelo-matematico"><span class="header-section-number">1.4</span> MODELO MATEMATICO</h2>
<p><span class="math display">
y_{ij} = \mu + \tau_i + \epsilon_{ij}
</span></p>
<p><span class="math inline">i=1, ..., I</span> es un indice acerca de los grupos o tratamientos.<br>
<span class="math inline">j=1, ..., J</span> es un indice acerca de las unidades experimentales por grupo.<br>
<span class="math inline">y_{ij}</span> son las observaciones de la variable respuesta<br>
<span class="math inline">\mu</span> es la media general de todas las observaciones.<br>
<span class="math inline">\tau_i</span> es el efecto del i-ésimo tratamiento.<br>
<span class="math inline">\epsilon_{ij}</span> es el termino de error, siendo <span class="math inline">\epsilon_{ij}</span> ~ N (0, <span class="math inline">\sigma^2</span>) independientes.</p>
</section>
<section id="ejemplo-1-echeverria-sp." class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="ejemplo-1-echeverria-sp."><span class="header-section-number">1.5</span> EJEMPLO 1 ~ ECHEVERRIA SP.</h2>
<p>Se está llevando a cabo un estudio para evaluar el efecto de diferentes métodos de riego en la adaptación de plantas de <em>Echeverria sp.</em> en la región de la puna. Se tiene tres métodos: riego por goteo, riego por aspersión y riego manual. Se desea determinar si existe alguna diferencia significativa en la longitud de las raices de las plantas de <em>Echeverria sp.</em> debido a los diferentes metodos de riego. Se sabe que otros factores como la temperatura, afectan a la adaptación pero en este experimento dichos factores se mantendran constantes.</p>
<section id="repeticion-y-aleatorizacion" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="repeticion-y-aleatorizacion"><span class="header-section-number">1.5.1</span> REPETICION Y ALEATORIZACION</h3>
<p>Para realizar el estudio, se seleccionan al azar 51 plantas y se las asigna aleatoriamente a uno de los tres métodos de riego. Esto puede realizarse por medio de un sorteo, por ejemplo:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7638</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">factor</span>( <span class="fu">rep</span>( <span class="fu">c</span>(<span class="st">"goteo"</span>, <span class="st">"aspersion"</span>, <span class="st">"manual"</span>), <span class="at">each =</span> <span class="dv">17</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>met <span class="ot">&lt;-</span> <span class="fu">sample</span>( f, <span class="dv">51</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">51</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>plantas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">planta=</span>n, <span class="at">metodo=</span>met )</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>plantas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   planta    metodo
1       1    manual
2       2     goteo
3       3     goteo
4       4    manual
5       5 aspersion
6       6    manual
7       7 aspersion
8       8 aspersion
9       9 aspersion
10     10    manual
11     11    manual
12     12 aspersion
13     13    manual
14     14 aspersion
15     15 aspersion
16     16     goteo
17     17     goteo
18     18 aspersion
19     19     goteo
20     20 aspersion
21     21 aspersion
22     22 aspersion
23     23    manual
24     24 aspersion
25     25    manual
26     26 aspersion
27     27     goteo
28     28 aspersion
29     29     goteo
30     30    manual
31     31     goteo
32     32     goteo
33     33 aspersion
34     34     goteo
35     35    manual
36     36    manual
37     37    manual
38     38 aspersion
39     39     goteo
40     40     goteo
41     41    manual
42     42     goteo
43     43 aspersion
44     44     goteo
45     45     goteo
46     46    manual
47     47    manual
48     48     goteo
49     49    manual
50     50     goteo
51     51    manual</code></pre>
</div>
</div>
<p>La repetición permite que puedan medirse varias longitudes de raíces en cada método de riego, en vez de solo una. Al tener unidades experimentales repetidas en cada nivel del factor tratamiento, la varianza del error experimental se puede calcular a partir de los datos, y esta varianza se comparará con los efectos de los tratamientos. Si la variabilidad entre medias de los tratamientos no es mayor que la varianza del error experimental, las diferencias entre tratamientos probablemente se deban a diferencias en las unidades experimentales asignadas a cada tratamiento. Sin repeticiones es imposible saber si las diferencias de tratamientos son reales o una manifestacion aleatoria de diferencias de las unidades experimentales. La aleatorización de las unidades experimentales en cada tratamiento, a su vez, garantiza la validez del experimento frente a sesgos provocados por otras variables ocultas. En el ejemplo de Echeverria, la aleatorización evita que las variables ocultas (como la variabilidad del sustrato, ubicacion de las plantas) sesgen el efecto del riego en el crecimiento de las raíces.</p>
</section>
<section id="objetivo" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="objetivo"><span class="header-section-number">1.5.2</span> OBJETIVO</h3>
<p>El objetivo del estudio es comparar el efecto de tres tipo de riego en el crecimiento de las raíces de plantas de Echeverria sp.</p>
</section>
<section id="unidades-experimentales" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="unidades-experimentales"><span class="header-section-number">1.5.3</span> UNIDADES EXPERIMENTALES</h3>
<p>Cada unas las plantas de Echeverria sp</p>
</section>
<section id="unidades-de-observacion" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="unidades-de-observacion"><span class="header-section-number">1.5.4</span> UNIDADES DE OBSERVACION</h3>
<p>Las raíces de plantas de Echeverria sp.</p>
</section>
<section id="variable-respuesta-o-variable-dependiente" class="level3" data-number="1.5.5">
<h3 data-number="1.5.5" class="anchored" data-anchor-id="variable-respuesta-o-variable-dependiente"><span class="header-section-number">1.5.5</span> VARIABLE RESPUESTA O VARIABLE DEPENDIENTE</h3>
<p>Longitud de raices de plantas de Echeverria sp.</p>
</section>
<section id="variable-independiente" class="level3" data-number="1.5.6">
<h3 data-number="1.5.6" class="anchored" data-anchor-id="variable-independiente"><span class="header-section-number">1.5.6</span> VARIABLE INDEPENDIENTE</h3>
<p>Metodo de riego con 3 niveles: goteo, aspersión y manual.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"echeverria.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [51 × 2] (S3: tbl_df/tbl/data.frame)
 $ Metodo: chr [1:51] "goteo" "aspersion" "manual" "goteo" ...
 $ Long  : num [1:51] 2.9 2.63 2.78 2.65 2.71 2.87 2.93 2.94 2.9 2.78 ...</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  Metodo     Long
  &lt;chr&gt;     &lt;dbl&gt;
1 goteo      2.9 
2 aspersion  2.63
3 manual     2.78
4 goteo      2.65
5 aspersion  2.71
6 manual     2.87</code></pre>
</div>
</div>
</section>
<section id="variables-ocultas" class="level3" data-number="1.5.7">
<h3 data-number="1.5.7" class="anchored" data-anchor-id="variables-ocultas"><span class="header-section-number">1.5.7</span> VARIABLES OCULTAS</h3>
<p>Las variables que pueden afectar el crecimiento de las raíces de las plantulas y que no se tuvieron en cuenta en este experimento: ubicacion de las plantas, tipo de sustrato, exposicion solar.</p>
<div class="quarto-video ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/Oc3wecPCROY" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="analisis-exploratorio" class="level3" data-number="1.5.8">
<h3 data-number="1.5.8" class="anchored" data-anchor-id="analisis-exploratorio"><span class="header-section-number">1.5.8</span> ANALISIS EXPLORATORIO</h3>
<p>Se realizará un analisis mediante medidas de resumen y grafico de cajas.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Metodo) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">minimo =</span> <span class="fu">round</span>(<span class="fu">min</span>(Long), <span class="dv">2</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Long), <span class="dv">2</span>),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">desvio =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Long), <span class="dv">2</span>),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">asimetria =</span> <span class="fu">round</span>(<span class="fu">skewness</span>(Long), <span class="dv">2</span>),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">round</span>(<span class="fu">median</span>(Long), <span class="dv">2</span>),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">CV =</span> <span class="fu">round</span>((desvio<span class="sc">/</span>media<span class="sc">*</span><span class="dv">100</span>),<span class="dv">2</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">round</span>(<span class="fu">max</span>(Long), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 8
  Metodo    minimo media desvio asimetria mediana    CV maximo
  &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 aspersion   2.3   2.81   0.18     -0.93    2.83  6.41   3.17
2 goteo       2.53  2.81   0.15     -0.59    2.88  5.34   2.98
3 manual      2.51  2.74   0.15      0.36    2.74  5.47   3.07</code></pre>
</div>
</div>
<p>Se observa que el mínimo de longitud de raiz es de 2.3 cm con el método de riego por aspersión. La longitud de raiz promedio es igual para los método goteo y aspersión (2.81 cm). El desvío de los datos con respecto a la media es de 0.15 cm para los métodos goteo y manual, mientras que para aspersión es 0.18 cm. Presentan asimetría negativa en sus datos los método de riego por aspersión y goteo. La menor mediana lo presentó el metodo manual, en donde el 50% de las plantas presentaron una longitud de raices hasta 2.74 cm.</p>
<p>Los coeficientes de variación para los tres métodos son bajos, lo cual nos indica homogeneidad en los datos.</p>
<p>La maxima longitud de raiz se encontró en el método riego por aspersion (3.17 cm).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Metodo, <span class="at">y =</span> Long)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Longitud de raices"</span>, <span class="at">x =</span> <span class="st">"Tratamiento"</span>, <span class="at">y =</span> <span class="st">"Long"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="001.dca_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<pre><code></code></pre>
<p>Se observa que el tratamiento riego por aspersión es el que presente menor rango intercuartilico, sin embargo presentan un valor atípico en su parte inferior.</p>
<p>Se observa que los tres metodos presentan asimetria en la distribucion de sus datos.</p>
<p>La mayor mediana se observa en el tratamiento riego por goteo.</p>
<p>Es posible que no se encuentren diferencias estadisticas significativas entre los tratamientos.</p>
<div class="quarto-video ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/UU-fD2qce3Y" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="modelo-matematico-1" class="level3" data-number="1.5.9">
<h3 data-number="1.5.9" class="anchored" data-anchor-id="modelo-matematico-1"><span class="header-section-number">1.5.9</span> MODELO MATEMATICO</h3>
<p>El modelo matemático para un DCA es:</p>
<p><span class="math display">
y_{ij} = \mu + \tau_i + \epsilon_{ij}
</span></p>
<p>Siendo,</p>
<p><span class="math inline">i= aspersion, goteo, manual</span><br>
<span class="math inline">j=1, ..., 17</span> para cada tratamiento<br>
<span class="math inline">y_{ij}</span> son las observaciones de longitud de raiz.<br>
<span class="math inline">\mu</span> es la media general de todas las observaciones.<br>
<span class="math inline">\tau_i</span> es el efecto del i-ésimo método de riego.<br>
<span class="math inline">\epsilon_{ij}</span> es el termino de error, siendo <span class="math inline">\epsilon_{ij}</span> ~ N (0, <span class="math inline">\sigma^2</span>) independientes.</p>
</section>
<section id="hipotesis-de-planteo" class="level3" data-number="1.5.10">
<h3 data-number="1.5.10" class="anchored" data-anchor-id="hipotesis-de-planteo"><span class="header-section-number">1.5.10</span> HIPOTESIS DE PLANTEO</h3>
<p>La hipotesis nula del modelo es</p>
<p><span class="math inline">Ho: \mu_{aspersion}=\mu_{goteo}=\mu_{manual}</span> o <span class="math inline">\tau_{aspersion}=\tau_{goteo}=\tau_{manual}</span> versus la hipotesis alternativa <span class="math inline">H1:</span> al menos una media es diferente a las demás o al menos dos efectos de tratamientos son diferentes.</p>
</section>
<section id="suma-de-cuadrados" class="level3" data-number="1.5.11">
<h3 data-number="1.5.11" class="anchored" data-anchor-id="suma-de-cuadrados"><span class="header-section-number">1.5.11</span> SUMA DE CUADRADOS</h3>
<p>Suma de cuadrado total (SCT) = Suma de cuadrados de tratamientos (SCTr)+ Suma de cuadrados del error experimental (SCEE)</p>
<p>Las sumas de cuadrados y los cuadrados medios y su calculo se observan en la siguiente tabla:</p>
<table class="table">
<thead>
<tr class="header">
<th>Fuente de variacion</th>
<th>g.l.</th>
<th>SC</th>
<th>CM</th>
<th>F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tratamiento</td>
<td>I-1</td>
<td>SCTr</td>
<td>CMTr</td>
<td>CMTr/CMEE</td>
</tr>
<tr class="even">
<td>Error</td>
<td>IJ-I</td>
<td>SCEE</td>
<td>CMEE</td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>IJ-1</td>
<td>SCT</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Bajo la hipótesis nula el valor F sigue una distribución F de Snedecor con I-1 y IJ-I grados de libertad.</p>
</section>
<section id="anova" class="level3" data-number="1.5.12">
<h3 data-number="1.5.12" class="anchored" data-anchor-id="anova"><span class="header-section-number">1.5.12</span> ANOVA</h3>
<p>Esta tabla de ANOVA con las sumas de cuadrados, grados de libertad y cuadrados medios puede visualizarse con la funcion <em>aov.</em></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">aov</span>(Long<span class="sc">~</span>Metodo, <span class="at">data=</span>datos)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Metodo       2 0.0485 0.02425   0.921  0.405
Residuals   48 1.2644 0.02634               </code></pre>
</div>
</div>
<p>La ultima columna es el p-valor y es la probabilidad de, bajo la hipotesis nula verdadera, exceder el valor de F calculado.</p>
<p>Con un nivel de significacion (<span class="math inline">\alpha</span>) de 0.05 y un p-valor de 0.405 no se rechaza la Ho.</p>
<div class="quarto-video ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/KRHnopFuRc4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="verificacion-de-los-supuestos-del-anova" class="level3" data-number="1.5.13">
<h3 data-number="1.5.13" class="anchored" data-anchor-id="verificacion-de-los-supuestos-del-anova"><span class="header-section-number">1.5.13</span> VERIFICACION DE LOS SUPUESTOS DEL ANOVA</h3>
<p>Los supuestos que se comprobaran son los de homogeneidad de varianzas, normalidad de residuos e independencia de los errores.</p>
<p><strong>Graficamente</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>( <span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>) )</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo, <span class="at">which=</span><span class="dv">5</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo, <span class="at">which=</span><span class="dv">1</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo, <span class="at">which=</span><span class="dv">2</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(modelo) <span class="sc">~</span> n, <span class="at">main=</span><span class="st">"Residuals vs Exp. Unit"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="at">font.main=</span><span class="dv">1</span>,<span class="at">data=</span>datos)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="001.dca_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El primer grafico contiene los residuos estandarizados versus los niveles del factor tratamiento. El segundo grafico hacia la derecha contiene los residuos observados versus los ajustados. El tercer grafico es de los cuantiles teoricos de una distribucion normal versus los observados. El ultimo grafico, corresponde a los residuos versus las unidades experimentales.</p>
<p>El primer grafico muestra que la variabilidad de los residuos es mayor en el metodo riego por aspersion por lo que la homocedasticidad no se cumpliría.</p>
<p>El segundo grafico de residuos vs ajustados muestra que los valores ajustados aumentan a medida que aumenta los valores de residuos, sin embargo no es claro acerca de la homocedasticidad.</p>
<p>El tercer grafico, indica que cuanto mas cerca de la recta se encuentran los puntos se cumple la distribucion normal de los residuos.</p>
<p>El supuesto más crítico para aplicar este modelo es la independencia de los errores experimentales, el cual se cumple si se ha realizado una aleatorizacion adecuada de las unidades experimentales a los niveles del factor y si existe un adecuado numero de repeticiones. En el ultimo gráfico no se observa ningun patrón o tendencia en los residuos por lo que este supuesto se cumpliría.</p>
<p><strong>Homogeneidad de Varianzas ~ Test de Levenne</strong></p>
<p>La hipotesis nula de este test es Ho: las varianzas de los tratamientos son homogeneas versus lo contrario.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(<span class="fu">resid</span>(modelo), datos<span class="sc">$</span>Metodo, <span class="at">center=</span>mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
      Df F value Pr(&gt;F)
group  2  0.0275 0.9729
      48               </code></pre>
</div>
</div>
<p>Con un p-valor (=0.9729) mayor al nivel de significación (<span class="math inline">\alpha=0.05</span>) no se rechaza la Ho.</p>
<p>Por lo tanto se concluye que las varianzas de los tratamientos son homogeneas.</p>
<p><strong>Normalidad de los residuos ~ Test de Kolmogorov Smirnov</strong></p>
<p>La hipotesis nula de este test es Ho: los residuos tienen distribucion normal versus lo contrario.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(<span class="fu">resid</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  resid(modelo)
D = 0.11487, p-value = 0.09026</code></pre>
</div>
</div>
<p>Con un p-valor (=0.09026) mayor al nivel de significación (<span class="math inline">alpha=0.05</span>) no se rechaza la Ho.</p>
<p>Por lo tanto se concluye que los residuos se distribuyen en forma normal.</p>
<p>Una vez que se comprobó que los supuestos del modelo se cumplen, las conclusiones que se obtengan del mismo son válidas.</p>
<div class="quarto-video ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/Z9lABKV2EK4" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="conclusiones-del-modelo-planteado" class="level3" data-number="1.5.14">
<h3 data-number="1.5.14" class="anchored" data-anchor-id="conclusiones-del-modelo-planteado"><span class="header-section-number">1.5.14</span> CONCLUSIONES DEL MODELO PLANTEADO</h3>
<p>Se concluye que todos los efectos de los metodos de riego aplicado son iguales (<span class="math inline">F_{(2, 48)}=0.921, p-value =0.405</span>) a un nivel de significacion de <span class="math inline">\alpha = 0.05</span>.</p>
</section>
<section id="confiabilidad-del-modelo" class="level3" data-number="1.5.15">
<h3 data-number="1.5.15" class="anchored" data-anchor-id="confiabilidad-del-modelo"><span class="header-section-number">1.5.15</span> CONFIABILIDAD DEL MODELO</h3>
<p>Se calculará el coeficiente de variación (CV) y el coeficiente de determinación (<span class="math inline">r^2</span>). Se tolera un CV de hasta 30%, aunque en condiciones controladas este valor no debe superar el 10%. Mientras que el <span class="math inline">r^2</span> cuanto mas cercano a 1 mejor prediccion del modelo.</p>
<p><span class="math inline">CV = \frac {CMEE}{\bar{x}}</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># coeficiente de variación</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sqrt</span>(<span class="fl">0.02634</span>))<span class="sc">/</span><span class="fu">mean</span>(datos<span class="sc">$</span>Long)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.823201</code></pre>
</div>
</div>
<p>El coeficiente de variacion del modelo es 5.82%.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#R2</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Long<span class="sc">~</span>Metodo, <span class="at">data=</span>datos)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>resumen.modelo<span class="ot">=</span><span class="fu">summary</span>(modelo)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>resumen.modelo<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03694676</code></pre>
</div>
</div>
<p>El valor de <span class="math inline">r^2</span> es 0.037, es decir es muy bajo, por lo tanto tiene poco poder explicativo.</p>
<div class="quarto-video ratio ratio-16x9"><iframe src="https://www.youtube.com/embed/Fk2mpBgFhcM" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
</section>
<section id="ejemplo-2-terneza-de-carne" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="ejemplo-2-terneza-de-carne"><span class="header-section-number">1.6</span> EJEMPLO 2 ~ TERNEZA DE CARNE</h2>
<p>Se lleva a cabo un estudio para evaluar el efecto de diferentes temperaturas de cocción en la terneza de los filetes de res. Se tiene cuatro temperaturas de cocción: 50 C, 60 C, 80 C y 120 C. Se desea determinar si hay diferencias significativas en la terneza entre las diferentes temperaturas de cocción.</p>
<p>Para llevar a cabo la investigación, se decide utilizar un diseño completamente al azar. Se seleccionaron al azar 32 filetes de res y se los asigna aleatoriamente a una de las cuatro temperaturas de cocción.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear los vectores</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>temperatura <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"50"</span>, <span class="st">"60"</span>, <span class="st">"80"</span>, <span class="st">"120"</span>), <span class="at">each =</span> <span class="dv">8</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>terneza <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">10.43</span>, <span class="fl">11.35</span>, <span class="fl">16.36</span>, <span class="fl">12.19</span>, <span class="fl">12.36</span>, <span class="fl">16.80</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>             <span class="fl">13.29</span>, <span class="fl">8.45</span>, <span class="fl">14.07</span>, <span class="fl">14.75</span>, <span class="fl">19.42</span>, <span class="fl">17.00</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>             <span class="fl">17.12</span>, <span class="fl">16.30</span>, <span class="fl">14.44</span>, <span class="fl">21.00</span>, <span class="fl">15.39</span>, <span class="fl">8.49</span>, </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>             <span class="fl">15.96</span>, <span class="fl">12.67</span>, <span class="fl">11.01</span>, <span class="fl">13.38</span>, <span class="fl">11.12</span>, <span class="fl">11.95</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>             <span class="fl">25.24</span>, <span class="fl">22.27</span>, <span class="fl">29.34</span>, <span class="fl">27.42</span>, <span class="fl">23.81</span>, <span class="fl">30.51</span>, </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>             <span class="fl">28.19</span>, <span class="fl">26.17</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el dataframe</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(temperatura, terneza)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="preguntas-orientadoras" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="preguntas-orientadoras"><span class="header-section-number">1.7</span> PREGUNTAS ORIENTADORAS</h2>
<ol type="1">
<li><p>¿Que es un ANOVA a un factor y cual es su proposito en el diseño de experimentos?</p></li>
<li><p>¿Cuales son los supuestos subyacentes del ANOVA a un factor y por que son importantes?</p></li>
<li><p>¿Que es un factor en el contexto del ANOVA y como se relaciona con las variables independientes y dependientes del estudio?</p></li>
<li><p>¿Que es una variable dependiente y como se mide en el ANOVA a un factor?</p></li>
<li><p>¿Cuales son los pasos principales para llevar a cabo un ANOVA a un factor?</p></li>
<li><p>¿Que es la suma de cuadrados y como se calcula en el ANOVA a un factor?</p></li>
<li><p>¿Como se calculan los grados de libertad y cual es su importancia en el ANOVA a un factor?</p></li>
<li><p>¿Que es el valor F y cómo se interpreta en el ANOVA a un factor?</p></li>
<li><p>¿Que es la significancia estadística y como se determina en el ANOVA a un factor?</p></li>
<li><p>¿Como se interpreta la salida de un análisis de ANOVA a un factor?</p></li>
<li><p>¿Como se mide la confiabilidad del modelo planteado con este diseño?</p></li>
<li><p>¿Cuales son las limitaciones y consideraciones importantes a tener en cuenta al realizar un ANOVA a un factor?</p></li>
</ol>
</section>
<section id="recursos-recomendados" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="recursos-recomendados"><span class="header-section-number">1.8</span> RECURSOS RECOMENDADOS</h2>
<p><strong>BIBLIOGRAFIA</strong></p>
<p>Melo, O. O., López, L. A., &amp; Melo, S. E. (2007).&nbsp;<em>Diseño de experimentos: métodos y aplicaciones</em>. Universidad Nacional de Colombia. Facultad de Ciencias. Cap 1 y 5. Disponible en: https://repositorio.unal.edu.co/handle/unal/83614</p>
<p>Lawson, J. (2014).&nbsp;<em>Design and Analysis of Experiments with R</em>&nbsp;(Vol. 115). CRC press. Cap 1 y 2. Disponible en: https://elearning.unite.it/pluginfile.php/221606/mod_resource/content/1/BookDOEwithR.pdf</p>
<p>Quinteros, H. (1997). Diseño Experimental. Facultad de Ciencias Agrarias, Universidad Nacional de Jujuy. Pags. 2-32.</p>
<p><strong>VIDEOS</strong></p>
<p><a href="https://www.youtube.com/watch?v=QV4WI1ZIdYU&amp;ab_channel=StatDOEbyRosaneRech" class="uri">https://www.youtube.com/watch?v=QV4WI1ZIdYU&amp;ab_channel=StatDOEbyRosaneRech</a></p>
<p><a href="https://www.youtube.com/watch?v=VmJ2l8iXsxo&amp;ab_channel=EugeneO%27Loughlin" class="uri">https://www.youtube.com/watch?v=VmJ2l8iXsxo&amp;ab_channel=EugeneO%27Loughlin</a></p>
<p><a href="https://www.youtube.com/watch?v=6OAil8VVVIM&amp;ab_channel=Jos%C3%A9Antonio%3AEstad%C3%ADsticaAplicada" class="uri">https://www.youtube.com/watch?v=6OAil8VVVIM&amp;ab_channel=Jos%C3%A9Antonio%3AEstad%C3%ADsticaAplicada</a></p>
<p><a href="https://www.youtube.com/watch?v=jGA73fD1Ywc&amp;ab_channel=ModelosEstadisticosFAUBA" class="uri">https://www.youtube.com/watch?v=jGA73fD1Ywc&amp;ab_channel=ModelosEstadisticosFAUBA</a></p>
<p><a href="https://www.youtube.com/watch?v=0NwA9xxxtHw&amp;ab_channel=DATAtab" class="uri">https://www.youtube.com/watch?v=0NwA9xxxtHw&amp;ab_channel=DATAtab</a></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>
